### ISSUE TITLE
Output parameters

### ISSUE THREAD

**Issue by JensDll** [JocaPC/CLR-Belgrade-SqlClient#13]
Hi, is there a recommended way to handle stored procedure output parameters?

**Comment by JocaPC** [comment]
Is this what you need: https://github.com/JocaPC/Belgrade-SqlClient/blob/master/Test/Master/BasicCommandTest.cs#L21

This test case executes internal procedure.

**Comment by JensDll** [comment]
Ah yes thank you that works.
