### ISSUE TITLE
Fails: Install-Package Belgrade.Sql.Client

### ISSUE THREAD

**Issue by saikiranmandhala** [JocaPC/CLR-Belgrade-SqlClient#2]
_**Tried installing it from console and NPM UI. But it fails with below exception.
Environment: VS 2015 - Win7**_ 

Install-Package : The underlying connection was closed: An unexpected error occurred on a send.At line:1 char:1
+ Install-Package Belgrade.Sql.Client
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by JocaPC** [comment]
I'm loading package successfully, so I believe that this is either transient issue or problem with your configuration. Package already has 8,657 total downloads.
