### ISSUE TITLE
Problem when use Belgrade-SqlClient with SignalR

### ISSUE THREAD

**Issue by meninjanho4788** [JocaPC/CLR-Belgrade-SqlClient#5]
When i use Belgrade-SqlClient with SignalR (Microsoft.AspNetCore.SignalR.Server)
I run my API (use Belgrade-SqlClient) so long and not end localhost:5000/api/header/menu ,it always loading.
I use default API (not use Belgrade-SqlClient) it can run without error.

My english is not good. Sorry for mistake.

**Comment by jovanpop-msft** [comment]
Hi, could you share some minimal sample that I can try?

**Comment by meninjanho4788** [comment]
Dear Jovanpop-Msft
Here is my example. I use data SQL 2016. You only connect one data it auto create data.
https://drive.google.com/file/d/0Bz4SjHjIqJkNOUE1M25xSFRUSUE/view
In file appsettings.json you change connect string to empty data sql
"SqlServerConnectionString": "Data Source=SQLEXPRESS;Initial Catalog=TestSignalR;Integrated Security=True"

You click WNew link it cant load data from Sql
API use Belgrade.Sql.Client : http://localhost:5000/api/header/menu/0    it load not end
API default : http://localhost:5000/api/content?lang=en		it end in one second

Thank you so much.
