### ISSUE TITLE
An overload to avoid writing direct to response.body

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [JocaPC/CLR-Belgrade-SqlClient#9]
Following your examples:

```
    [HttpGet]
    [Route("customer_details/{customerid:int}")]
    public async Task customer_details(int customerid)
    {
      await cmd
        .Proc("customer_details")
        .Param("customerid", customerid)
        .Stream(Response.Body, "{}");
    }
```

Works quite well, but i feel we lose all the other enabled `ASP.Net pipeline `features like `compression`, because we are writing directly to the  `Response.Body`

Please is it possible to have an overload that will work like this:

```
[HttpGet]
[Route("customer_details/{customerid:int}")]
public async Task<ActionResult> customer_details(int customerid)
{
  return Ok(await cmd
        .Proc("customer_details")
        .Param("customerid", customerid)
        .Stream("{}");
}
```
So we don't exit the ASP.Net pipeline by writing to `Response.Body`

Also this: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/request-response?view=aspnetcore-3.0

Thanks, again for this helper library!

**Comment by JocaPC** [comment]
Interesting suggestion.

There is a `GetString()` extension method https://github.com/JocaPC/Belgrade-SqlClient/blob/master/Code/Common/Extensions/IQueryExtensions.cs#L71 that returns string that you could provide as a result to `Ok()` method.

Here is an example how you can use it: https://github.com/JocaPC/Belgrade-SqlClient/blob/master/Test/Master/BasicQueryMapperTest.cs#L92

**Comment by CharlesOkwuagwu** [comment]
> Here is an example how you can use it: https://github.com/JocaPC/Belgrade-SqlClient/blob/master/Test/Master/BasicQueryMapperTest.cs#L92

I had tried something similar, before finding your library.
I simply returned a string from Dapper .... `Ok( json);` it results in a the json sent in "" ... wont this line do same?

https://github.com/JocaPC/Belgrade-SqlClient/blob/master/Code/Common/Extensions/IQueryExtensions.cs#L74

**Comment by JocaPC** [comment]
Yes, but is this exactly what you need? In that case you can use:

```
[HttpGet]
[Route("customer_details/{customerid:int}")]
public async Task<ActionResult> customer_details(int customerid)
{
  return Ok(await cmd
        .Proc("customer_details")
        .Param("customerid", customerid)
        .GetString("{}");
}
```

**Comment by CharlesOkwuagwu** [comment]
>GetString("{}");

This helps. Thanks.
